apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-app-deployment
  labels:
    app: cloud-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud-app
  template:
    metadata:
      labels:
        app: cloud-app
    spec:
      initContainers:
      - name: node-cloud-migrations
        image: augustinvct/cloud-app:latest
        env:
          - name: FOO
            value: bar
          - name: DB_USER
            value: root
        command: ["node", "/cloud-app/src/utils/createDb.js"]
        resources:
          requests:
            cpu: 250m
            memory: 512M
          limits:
            cpu: 250m
            memory: 512M
      containers:
      - name: node-cloud-app
        image: augustinvct/cloud-app:latest
        ports:
        - containerPort: 8080
        env:
          - name: FOO
            value: bar
        resources:
          requests:
            cpu: 250m
            memory: 512M
          limits:
            cpu: 250m
            memory: 512M

// 1. Ajouter en clair user + IP + password de cloudsql a l'env des containers ne pas commit ce fichier jusqu'a lundi
// 2. Faire echec quand les migrations ne passent pas 
// 3. Verifier avec Tableplus que les mig passent