apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-app-deployment
  labels:
    app: cloud-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud-app
  template:
    metadata:
      labels:
        app: cloud-app
    spec:
      initContainers:
      - name: node-cloud-migrations
        image: augustinvct/cloud-app:latest
        env:
          - name: JWT_KEY
            valueFrom:
              secretKeyRef:
                name: cloud-app
                key: jwt_key
          - name: MARIADB_USER
            value: linkup
          - name: MARIADB_HOST
            value: "34.89.141.140"
          - name: MARIADB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cloud-app
                key: mariadb_password
          - name: MARIADB_DATABASE
            value: linkup
        command: ["node", "/cloud-app/src/utils/createDb.js"]
        resources:
          requests:
            cpu: 250m
            memory: 512M
          limits:
            cpu: 250m
            memory: 512M
      containers:
      - name: node-cloud-app
        image: augustinvct/cloud-app:latest
        ports:
        - containerPort: 8080
        env:
          - name: JWT_KEY
            valueFrom:
              secretKeyRef:
                name: cloud-app
                key: jwt_key
          - name: MARIADB_USER
            value: linkup
          - name: MARIADB_HOST
            value: "34.89.141.140"
          - name: MARIADB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cloud-app
                key: mariadb_password
          - name: MARIADB_DATABASE
            value: linkup
        resources:
          requests:
            cpu: 250m
            memory: 512M
          limits:
            cpu: 250m
            memory: 512M